apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ditt-nav-arbeidsgiver
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{version}}
  team: {{team}}
  port: 3000
  ingresses:
    - https://arbeidsgiver-q.nav.no/min-side-arbeidsgiver/
  liveness:
    path: /min-side-arbeidsgiver/internal/isAlive
    initialDelay: 20
  readiness:
    path: /min-side-arbeidsgiver/internal/isReady
    initialDelay: 20
  vault:
    enabled: true
  env:
    - name: API_GATEWAY
      value: https://api-gw-q1.oera.no
    - name: Q0API_GATEWAY
      value: https://api-gw-q0.oera.no
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: LOGIN_URL
      value: https://loginservice-q.nav.no/login?redirect=https://arbeidsgiver-q.nav.no/min-side-arbeidsgiver/



